name: Gerar README Simples

on:
  # Permite executar o workflow manualmente
  workflow_dispatch:
  # Opcional: Executa uma vez, assim que o código for enviado (push) para a branch 'main'
  push:
    branches:
      - main

jobs:
  criar_readme:
    # O job será executado na última versão do Ubuntu
    runs-on: ubuntu-latest
    
    steps:
      # Passo 1: Faz o checkout do código
      - name: Checkout do Repositório
        uses: actions/checkout@v4
        
      # Passo 2: Cria o conteúdo do README usando comandos Shell
      - name: Criar Conteúdo do README
        run: |
          echo "# Esses são dados da minha conta profissional"
          echo ""
          echo "**[@romulosuperlogica](https://github.com/romulosuperlogica)** | Desenvolvedor | Contribuições Profissionais"
          echo "<p align="center">"
          echo "</p>"
          echo "Ficou com dúvida? Acesse diretamente meu perfil completo em [github.com/romulosuperlogica](https://github.com/romulosuperlogica)."
          
      # Passo 3: Commit e Push das alterações no README
      # Usamos uma Action de terceiros para fazer o commit de forma simples
      - name: Commit e Enviar o novo README.md
        uses: EndBug/add-and-commit@v9
        with:
          # A mensagem de commit que aparecerá no histórico
          message: 'docs: Criação inicial do README.md via GitHub Actions'
          # Especifica o arquivo a ser adicionado
          add: 'README.md'
          # Usa o token padrão para a Action
          token: ${{ secrets.GITHUB_TOKEN }}
