name: Gerar README Simples

on:
  # Permite executar o workflow manualmente
  workflow_dispatch:
  # Opcional: Executa uma vez, assim que o código for enviado (push) para a branch 'main'
  push:
    branches:
      - main

jobs:
  criar_readme:
    runs-on: ubuntu-latest
    
    steps:
      # Passo 1: Faz o checkout do código
      - name: Checkout do Repositório
        uses: actions/checkout@v4
        
      # Passo 2: Cria/Atualiza o conteúdo do README usando comandos Shell
      - name: Criar e Anexar Conteúdo ao README
        run: |
          # 1. Cria ou sobrescreve o arquivo README.md (use >)
          echo "# Esses são dados da minha conta profissional" > README.md
          
          # 2. Anexa as linhas seguintes (use >>)
          echo "" >> README.md
          echo "**[@romulosuperlogica](https://github.com/romulosuperlogica)** | Desenvolvedor | Contribuições Profissionais" >> README.md
          
          # 3. Escapando as aspas duplas (ou use aspas simples)
          echo '<p align="center">' >> README.md
          echo '</p>' >> README.md
          
          echo "Ficou com dúvida? Acesse diretamente meu perfil completo em [github.com/romulosuperlogica](https://github.com/romulosuperlogica)." >> README.md
          
      # Passo 3: Commit e Push das alterações no README
      - name: Commit e Enviar o novo README.md
        uses: EndBug/add-and-commit@v9
        with:
          # Define a mensagem de commit
          message: 'docs: Atualiza README.md com dados de perfil'
          # Especifica o arquivo a ser adicionado
          add: 'README.md'
          # Usa o token padrão do GitHub Actions
          token: ${{ secrets.GITHUB_TOKEN }}
