name: Gerar README Simples

on:
  # Permite executar o workflow manualmente
  workflow_dispatch:
  # Opcional: Executa uma vez, assim que o código for enviado (push) para a branch 'main'
  push:
    branches:
      - main

jobs:
  criar_readme:
    # O job será executado na última versão do Ubuntu
    runs-on: ubuntu-latest
    
    steps:
      # Passo 1: Faz o checkout do código
      - name: Checkout do Repositório
        uses: actions/checkout@v4
        
      # Passo 2: Cria o conteúdo do README usando comandos Shell
      - name: Criar Conteúdo do README
        run: |
          echo "# Nome do Meu Projeto Incrível" > README.md
          echo "" >> README.md
          echo "Este é um projeto simples e legal." >> README.md
          echo "Adicione mais detalhes sobre o que ele faz aqui." >> README.md
          echo "" >> README.md
          echo "## Como Rodar" >> README.md
          echo "\`npm install && npm start\`" >> README.md
          
      # Passo 3: Commit e Push das alterações no README
      # Usamos uma Action de terceiros para fazer o commit de forma simples
      - name: Commit e Enviar o novo README.md
        uses: EndBug/add-and-commit@v9
        with:
          # A mensagem de commit que aparecerá no histórico
          message: 'docs: Criação inicial do README.md via GitHub Actions'
          # Especifica o arquivo a ser adicionado
          add: 'README.md'
          # Usa o token padrão para a Action
          token: ${{ secrets.GITHUB_TOKEN }}
